---
- name: configure a linux VM with bazel to emulate a developer workstation
  become: yes
  hosts: all

  tasks:

    - name: add bazel gpg key
      apt_key:
        url: https://bazel.build/bazel-release.pub.gpg
        state: present

    - name: add bazel apt repo
      apt_repository:
        repo: deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8
        state: present

    - name: install bazel and dependencies
      apt:
        name:
          - unzip
          - patch
          - git
          - build-essential
          - bazel
          - golang
